# Generated by Django 4.0.1 on 2022-01-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArcGISWebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text='When this event was received.')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'ArcGIS Webhook',
                'verbose_name_plural': 'ArcGIS Webhooks',
            },
        ),
        migrations.AddIndex(
            model_name='arcgiswebhookmessage',
            index=models.Index(fields=['received_at'], name='webhook_lis_receive_3fd9b6_idx'),
        ),
    ]
