# Generated by Django 4.0.1 on 2022-01-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcgiswebhookmessage',
            name='event_name',
            field=models.TextField(default='edit_me', verbose_name='Event Name'),
            preserve_default=False,
        ),
    ]
