# Generated by Django 4.0.1 on 2022-04-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0002_arcgiswebhookmessage_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobKind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dotted_path', models.TextField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('periodic', models.BooleanField(default=False)),
                ('failed', models.BooleanField(blank=True, default=None, null=True)),
                ('last_run', models.DateTimeField(blank=True, default=None, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhook_listener.jobkind')),
            ],
        ),
    ]
