# Generated by Django 4.0.1 on 2022-04-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0004_rename_job_task_rename_jobkind_taskkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhook_listener.arcgiswebhookmessage'),
        ),
        migrations.AddField(
            model_name='taskkind',
            name='description',
            field=models.TextField(default='no description provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arcgiswebhookmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
