# Generated by Django 3.2.13 on 2022-04-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_listener', '0005_task_source_taskkind_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskKind',
        ),
    ]
